### ISSUE TITLE
NL overall

### ISSUE THREAD

**Issue by Dylantje** [akamming/domoticz-coronadashboard#1]
Dear..

Very nice plugin..
Only perhaps possible to make also a few devices for the whole country?

**Comment by akamming** [comment]
i don't understand your question. you have the devices for the whole country. If you specify one or more safety regions (veiligheids regio's), then you also get devices for those safety regions...

**Comment by Dylantje** [comment]
sorry... 
everything looking great...
Is missed some devices..

Thanks for the great work!!!
