### ISSUE TITLE
Utility titles too long

### ISSUE THREAD

**Issue by wkossen** [akamming/domoticz-coronadashboard#7]
Hi

The titles of the utility boxes for this plugin are too long which means the values overlay on the titles and are unreadable. At least, that happens to me. So something like "Corona Dashboard  - Intensive-Care Opnames' could better be shorted to 'CovidNL - IC-opnames' or something shorter like that.

**Comment by akamming** [comment]
These are just default names. Within domoticz you can change to whatever you like.

But if you can send me a list shortened names for the sensors i have no trouble  implementating...
